### ISSUE TITLE
User Error:

### ISSUE THREAD

**Issue by ghost** [chxlls/ticketbot#2]
In remove.js, the user part is not defined.

**Comment by gamer167** [comment]
WTF

**Comment by ghost** [comment]
What! What defines USER

**Comment by eshansalimi** [comment]
There is nothing that defines "user". I'm assuming "user" refers to `message.mentions.members.first()`

**Comment by dog1cool** [comment]
so its fixed right?

**Comment by eshansalimi** [comment]
No, but it's a simple fix to make yourself
