### ISSUE TITLE
Missing Script: Start

### ISSUE THREAD

**Issue by UncutModifiations** [chxlls/ticketbot#3]
I've tried looking and I can't fix it I passed it to my friends and they have no idea.
language = "nodejs"
run = "npm start"

npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-01-08T14_22_38_667Z-debug.log
exit status 1

**Comment by UncutModifiations** [comment]
If you could help that would be great

**Comment by eshansalimi** [comment]
Well, does it execute when you run `node index.js`? This is because `npm start`, as far as I know, is not standard, and you have to write in the script for `npm start` to work

Edit: Spelling

**Comment by Rizer2627** [comment]
Hello @UncutModifications , 
     Do you by chance have your package.json Installed? If so do you have a "start": "node index.js" in this package.json File?  Let me know!
     
  ```{
  "name": "ticket-tool-bot",
  "version": "0.0.1",
  "description": "A simple package.json.",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "index": "node index.js"
  },
  "dependencies": {
    "discord.js": "^12.5.1",
    "express": "^4.17.1",
    "graceful-fs": "^4.2.4",
    "quick.db": "^7.1.3"
  },
  "engines": {
    "node": "12.x"
  },
  "keywords": [
    "node",
    "bot",
    "discord"
  ]
}
```

**Comment by idkwhattoputhere121** [comment]
You can also do:
Node .
